[colors.bright]
black = "#555555"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[colors.normal]
black = "#000000"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[colors.primary]
background = "0xf9f5d7"
foreground = "0x3c3836"

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 16

[font.normal]
family = "InconsolataGo Nerd Font"

[scrolling]
history = 50000
multiplier = 3
