require("config.globals")
require("config.autocmds")
require("config.filetypes")
require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.commands")
require("config.lsp")
