require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "dockerfile",
        "javascript",
        "typescript",
        "tsx",
        "python",
        "c",
        "go",
        "gomod",
        "bash",
        "make",
        "markdown",
        "sql",
        "vim",
        "yaml",
        "html",
        "hcl",
    },
    auto_install = true,
    highlight = { enable = true, additional_vim_regex_highlighting = true },
    autopairs = { enable = true },
    incremental_selection = { enable = true },
    textobjects = { enable = true },
})
