#!/bin/bash

set -e

option=$(echo -e "[Cancel]\nShutdown\nReboot\nSuspend\nLogout" | rofi -dmenu -i)

if [[ $option = "Shutdown" ]]; then
	systemctl poweroff
elif [[ $option = "Reboot" ]]; then
	systemctl reboot
elif [[ $option = "Suspend" ]]; then
	systemctl suspend
elif [[ $option = "Logout" ]]; then
	i3-msg exit
fi
