export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv virtualenv-init -)"

export PATH=~/.npm-global/bin:$PATH

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export GOPATH="$HOME/go"
export PATH=$PATH:$HOME/go/bin
export PATH=$HOME/.nimble/bin:$PATH
